apiVersion: v1
kind: Service
metadata:
  name: gabi-service
spec:
  type: NodePort
  selector:
    app: gabi-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gabi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gabi-app
  template:
    metadata:
      labels:
        app: gabi-app
    spec:
      containers:
      - name: gabi-container
        image: wordbe/gabi:latest
        ports:
        - containerPort: 8080

